apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-final
  labels:
    app: capstone-final
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-final
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-final
    spec:
      containers:
        - image: kpeery/capstone-final
          imagePullPolicy: Always
          name: capstone-final
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-final
  labels:
    app: capstone-final
spec:
  type: LoadBalancer
  selector:
    app: capstone-final
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP